export interface TransactionReportResponse {
    id: number,
    uuid: string,
    transaction_id: string,
    invoice_no: string,
    transfer_no: string,
    status: boolean,
    user_id: number,
    author_id: number,
    profit_percent: number,
    profit_amount: number,
    system_amount: number,
    amount: number,
    tax_percent: number,
    tax_amount: number,
    sub_category_id: number,
    product_id: number,
    transaction_type: number,
    details: {
      point: number,
      price: number,
      cardType: string,
      currency: string,
      mainType: string,
      respCode: string,
      paymentType: string,
      paymentMethod: string,
      transactionId: string,
      transactionFee: string,
      rspDescription: string  
    },
    created_at: Date,
    updated_at: Date,
}